[package]
name = "usb-control-updater"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "usb-control-updater"
path = "src/main.rs"

[dependencies]
hex = { workspace = true }
libc = { workspace = true }
rustls-pemfile = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
system-upgrade = { path = "../system-upgrade" }
thiserror = { workspace = true }
wait-timeout = { workspace = true }

[dev-dependencies]
smcrypto = { workspace = true }
tar = { workspace = true }
tempfile = { workspace = true }
