export const IpcChannels = {
  tlsConnect: 'tls:connect',
  tlsDisconnect: 'tls:disconnect',
  tlsSend: 'tls:send',
  tlsApplyStateEvent: 'tls:apply-state-event',
  connectionStateChanged: 'connection:state-changed',
  dialogOpenFile: 'dialog:open-file',
  dialogSaveFile: 'dialog:save-file',
  dialogReadFile: 'dialog:read-file',
  dialogWriteFile: 'dialog:write-file',
  usbListStorageDevices: 'usb:list-storage-devices',
  windowMinimize: 'window:minimize',
  windowMaximize: 'window:maximize',
  windowClose: 'window:close',
} as const
