[package]
name = "system-upgrade"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "系统升级领域服务"

[dependencies]
base64 = { workspace = true }
hex = { workspace = true }
libc = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
smcrypto = { workspace = true }
tar = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
